web:
  image: nginx:latest
  ports:
    - "80"
    - "443"
  links:
    - "rails"
  environment:
    VIRTUAL_HOST: blog.dev.io
  volumes:
    - ./log/nginx:/var/log/nginx
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./docker/nginx/includes:/etc/nginx/includes
    - ./docker/nginx/custom-locations:/etc/nginx/custom-locations
    - ./docker/nginx/ssl:/etc/nginx/ssl
  volumes_from:
    - rails

rails:
  image: mc388/rails:latest
  command: bundle exec unicorn -E development -c config/unicorn.rb
  volumes:
    - ./:/var/www/html
  links:
    - mysql

mysql:
  image: mysql:latest
  ports:
    - "40012:3306"
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: pw
    MYSQL_DATABASE: blog
    MYSQL_USER: blog
    MYSQL_PASSWORD: blogpw
