POSTS_DIR: "posts"
LAST_IMPORT_FILE: "last_import"
GOOGLE_ANALYTICS_KEY: "UA-34358736-1"
CODECLIMATE_REPO_TOKEN: "f16d927e411871c0e616a5798fd52b86c6e44b3494ad69f98e04f539fece8268"
# mc388-markdown-blog
# DROPBOX_KEY: "y5zqajph3e1cqas"
# DROPBOX_SECRET: "m2t2znrk41pjc7l"
# DROPBOX_ACCESS_TOKEN: "x-fyZRLinisAAAAAAAAE0g3-e9P4fV47Cm1CVmSo0qJR_KubcsoBsN-7qgMAcz_U"

# mc388-markdown-blog2
DROPBOX_KEY: "2c17g9q82idr2pd"
DROPBOX_SECRET: "j4zjz9bjcqp4dl0"
DROPBOX_ACCESS_TOKEN: "x-fyZRLinisAAAAAAAAE02FAK86CZOu9dcFBk1ABjlVvGWBbOFgEijReZLQvQ6e_"
